# Association Rule Mining

### What is it?
Association Rule Mining is an unsupervised learning technique used to find relationships between items in large datasets.
It answers questions like: “If people buy X, what else are they likely to buy?”

### How it works

Step 1: Find frequent itemsets (items that appear together often).

Step 2: Generate rules from those itemsets.

Step 3: Evaluate rules using metrics:

Support → how frequently an itemset appears in the dataset.

Confidence → how often the rule is true.

Lift → how much stronger the rule is compared to random chance.

#### Simple Example

```
T1: Milk, Bread, Butter  
T2: Bread, Butter  
T3: Milk, Bread  
T4: Milk, Bread, Butter  
```

Rule: {Milk, Bread} → {Butter}

- Support = appears in 2/4 = 50%

- Confidence = (Milk & Bread & Butter) / (Milk & Bread) = 2/3 ≈ 66%

- Lift > 1 means positive association.

#### Real World Applications
Retail → Market Basket Analysis (Amazon, Walmart).

Recommendation Systems → “Users who listen to this song also like…”

Web Mining → Which web pages are visited together.

Healthcare → Which symptoms appear together.

#### Algorithms in Association Rule Mining
1. Apriori Algorithm (Most Common, Easy to Start With)

- Works by generating frequent itemsets step by step (breadth-first).

- Uses the Apriori property: “If an itemset is frequent, all its subsets must also be frequent.”

- Downside → slow on large datasets.

2. Eclat Algorithm

- Uses vertical data format (items with transaction IDs).

- Finds frequent itemsets using set intersections.

- Faster than Apriori in some cases

3. FP-Growth (Frequent Pattern Growth)

- Builds a tree structure (FP-tree) to represent transactions.

- Much faster than Apriori because it avoids generating too many candidate itemsets.

- Used in big data frameworks like Apache Spark MLlib.

In [1]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in d:\a code\ml-playground\.venv\lib\site-packages (from mlxtend) (1.16.1)
Requirement already satisfied: numpy>=1.16.2 in d:\a code\ml-playground\.venv\lib\site-packages (from mlxtend) (2.3.2)
Requirement already satisfied: pandas>=0.24.2 in d:\a code\ml-playground\.venv\lib\site-packages (from mlxtend) (2.3.2)
Requirement already satisfied: scikit-learn>=1.3.1 in d:\a code\ml-playground\.venv\lib\site-packages (from mlxtend) (1.7.1)
Requirement already satisfied: matplotlib>=3.0.0 in d:\a code\ml-playground\.venv\lib\site-packages (from mlxtend) (3.10.5)
Requirement already satisfied: joblib>=0.13.2 in d:\a code\ml-playground\.venv\lib\site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: contourpy>=1.0.1 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (25.0)
Requirement already satisfied: pillow>=8 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in d:\a code\ml-playground\.venv\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\a code\ml-playground\.venv\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\a code\ml-playground\.venv\lib\site-packages (from pandas>=0.24.2->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in d:\a code\ml-playground\.venv\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in d:\a code\ml-playground\.venv\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.6.0)
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 5.6 MB/s eta 0:00:01
   ------------------------------- -------- 1.0/1.4 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 2.8 MB/s  0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
# Sample dataset (transactions in one-hot encoded form)
dataset = [
    ['Milk', 'Bread', 'Butter'],
    ['Bread', 'Butter'],
    ['Milk', 'Bread'],
    ['Milk', 'Bread', 'Butter']
]

In [4]:
# Convert dataset into DataFrame (one-hot encoding)
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [5]:
df

   Bread  Butter   Milk
0   True    True   True
1   True    True  False
2   True   False   True
3   True    True   True

In [7]:
# Step 1: Find frequent itemsets
frequent_itemsets = apriori(df, min_support=0.5, use_colnames=True)
frequent_itemsets

   support               itemsets
0     1.00                (Bread)
1     0.75               (Butter)
2     0.75                 (Milk)
3     0.75        (Bread, Butter)
4     0.75          (Bread, Milk)
5     0.50         (Milk, Butter)
6     0.50  (Bread, Milk, Butter)

In [8]:
# Step 2: Generate rules
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
rules

d:\A Code\ML-Playground\.venv\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:186: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Bread),(Butter),1.00,0.75,0.75,0.750000,1.000000,1.0,0.0000,1.00,0.000000,0.75,0.000000,0.875000
1,(Butter),(Bread),0.75,1.00,0.75,1.000000,1.000000,1.0,0.0000,inf,0.000000,0.75,0.000000,0.875000
2,(Bread),(Milk),1.00,0.75,0.75,0.750000,1.000000,1.0,0.0000,1.00,0.000000,0.75,0.000000,0.875000
3,(Milk),(Bread),0.75,1.00,0.75,1.000000,1.000000,1.0,0.0000,inf,0.000000,0.75,0.000000,0.875000
4,(Milk),(Butter),0.75,0.75,0.50,0.666667,0.888889,1.0,-0.0625,0.75,-0.333333,0.50,-0.333333,0.666667
5,(Butter),(Milk),0.75,0.75,0.50,0.666667,0.888889,1.0,-0.0625,0.75,-0.333333,0.50,-0.333333,0.666667
6,"(Bread, Milk)",(Butter),0.75,0.75,0.50,0.666667,0.888889,1.0,-0.0625,0.75,-0.333333,0.50,-0.333333,0.666667
7,"(Bread, Butter)",(Milk),0.75,0.75,0.50,0.666667,0.888889,1.0,-0.0625,0.75,-0.333333,0.50,-0.333333,0.666667
8,"(Milk, Butter)",(Bread),0.50,1.00,0.50,1.000000,1.000000,1.0,0.0000,inf,0.000000,0.50,0.000000,0.750000
9,(Bread),"(Milk, Butter)",1.00,0.50,0.50,0.500000,1.000000,1.0,0.0000,1.00,0.000000,0.50,0.000000,0.750000
10,(Milk),"(Bread, Butter)",0.75,0.75,0.50,0.666667,0.888889,1.0,-0.0625,0.75,-0.333333,0.50,-0.333333,0.666667
11,(Butter),"(Bread, Milk)",0.75,0.75,0.50,0.666667,0.888889,1.0,-0.0625,0.75,-0.333333,0.50,-0.333333,0.666667

In [9]:
print("\nAssociation Rules:\n", rules[['antecedents','consequents','support','confidence','lift']])

Association Rules:
         antecedents      consequents  support  confidence      lift
0           (Bread)         (Butter)     0.75    0.750000  1.000000
1          (Butter)          (Bread)     0.75    1.000000  1.000000
2           (Bread)           (Milk)     0.75    0.750000  1.000000
3            (Milk)          (Bread)     0.75    1.000000  1.000000
4            (Milk)         (Butter)     0.50    0.666667  0.888889
5          (Butter)           (Milk)     0.50    0.666667  0.888889
6     (Bread, Milk)         (Butter)     0.50    0.666667  0.888889
7   (Bread, Butter)           (Milk)     0.50    0.666667  0.888889
8    (Milk, Butter)          (Bread)     0.50    1.000000  1.000000
9           (Bread)   (Milk, Butter)     0.50    0.500000  1.000000
10           (Milk)  (Bread, Butter)     0.50    0.666667  0.888889
11         (Butter)    (Bread, Milk)     0.50    0.666667  0.888889